from helper import*

extras = Player('Extra',False,0,0,True)

sachin=Player('S Tendulkar',False, 0, 0, True)
sehwag=Player('V Sehwag',False, 0, 0, True)
gambhir=Player('G Gambhir',False, 0, 0, True)
kohli=Player('V Kohli',False, 0, 0, True)
yuvraj=Player('Yuvraj Singh',False, 0, 0, True)
dhoni=Player('M S Dhoni',False, 0, 0, True)
raina=Player('S Raina',False, 0, 0, True)
ashwin=Player('R Ashwin',False, 0, 0, True)
zaheer=Player('Zaheer Khan',False, 0, 0, True)
nehra=Player('A Nehra',False, 0, 0, True)
sreesanth=Player('S Sreesanth',False, 0, 0, True)

hayden=Player('M Hayden',False, 0, 0, True)
gilchrist=Player('A Gilchrist',False, 0, 0, True)
ponting=Player('R Ponting',False, 0, 0, True)
clarke=Player('M Clarke',False, 0, 0, True)
hussey=Player('M Hussey',False, 0, 0, True)
watson=Player('S Watson',False, 0, 0, True)
white=Player('C White',False, 0, 0, True)
hogg=Player('B Hogg',False, 0, 0, True)
johnson=Player('M Johnson',False, 0, 0, True)
lee=Player('B Lee',False, 0, 0, True)
tait=Player('S Tait',False, 0, 0, True)

tharanga=Player('U Tharanga',False, 0, 0, True)
dilshan=Player('T Dilshan',False, 0, 0, True)
sangakkara=Player('K Sangakkara',False, 0, 0, True)
jayawardene=Player('M Jayawardene',False, 0, 0, True)
samaraweera=Player('T Samaraweera',False, 0, 0, True)
kapugedera=Player('C Kapugedera',False, 0, 0, True)
kulashekara=Player('N Kulashekara',False, 0, 0, True)
perera=Player('D Perera',False, 0, 0, True)
randiv=Player('S Randiv',False, 0, 0, True)
malinga=Player('L Malinga',False, 0, 0, True)
murali=Player('M Muralitharan',False, 0, 0, True)

smith=Player('G Smith',False, 0, 0, True)
amla=Player('H Amla',False, 0, 0, True)
kallis=Player('J Kallis',False, 0, 0, True)
devilliers=Player('A B de Villiers',False, 0, 0, True)
duminy=Player('J P Duminy',False, 0, 0, True)
duplessis=Player('Faf du Plessis',False, 0, 0, True)
vanvyk=Player('M Van Vyk',False, 0, 0, True)
botha=Player('J Botha',False, 0, 0, True)
peterson=Player('R Peterson',False, 0, 0, True)
morkel=Player('M Morkel',False, 0, 0, True)
steyn=Player('D Steyn',False, 0, 0, True)
