from helper import*

extras = Player(name='Extra')

dhawan=Player(name='S Dhawan',attr=PlayerAttr(batting=8))
rsharma=Player(name='R Sharma', attr=PlayerAttr(batting=8))
kohli=Player(name='V Kohli',attr=PlayerAttr(batting=8, iscaptain=True))
klrahul=Player(name='K L Rahul',attr=PlayerAttr(batting=7))
dkarthik=Player(name='D Karthik',attr=PlayerAttr(batting=6))
dhoni=Player(name='M S Dhoni',attr=PlayerAttr(batting=7,iskeeper=True))
hpandya=Player(name='H Pandya',attr=PlayerAttr(bowling=6,batting=6))
ashwin=Player(name='R Ashwin',attr=PlayerAttr(bowling=8))
bkumar=Player(name='B Kumar',attr=PlayerAttr(bowling=8))
shami=Player(name='M Shami',attr=PlayerAttr(bowling=8))
bumrah=Player(name='J Bumrah',attr=PlayerAttr(bowling=9))

warner=Player(name='D Warner',attr=PlayerAttr(batting=8))
finch=Player(name='A Finch',attr=PlayerAttr(batting=7,iscaptain=True))
khawaja=Player(name='U Khawaja',attr=PlayerAttr(batting=7))
ssmith=Player(name='S Smith',attr=PlayerAttr(batting=8))
maxwell=Player(name='G Maxxwell',attr=PlayerAttr(batting=7,bowling=6))
stoinis=Player(name='M Stoinis',attr=PlayerAttr(bowling=6, batting=6))
carey=Player(name='A Carey', attr=PlayerAttr(batting=6, iskeeper=True))
cummins=Player(name='P Cummins',attr=PlayerAttr(bowling=8))
starc=Player(name='M Starc',attr=PlayerAttr(bowling=8))
bdorff=Player(name='J Behrendorff',attr=PlayerAttr(bowling=7))
zampa=Player(name='A Zampa',attr=PlayerAttr(bowling=7))

guptill=Player(name='M Guptill',attr=PlayerAttr(batting=8))
munro=Player(name='C Munro',attr=PlayerAttr(batting=7))
williamson=Player(name='K Williamson',attr=PlayerAttr(batting=8, iscaptain=True))
rtaylor=Player(name='R Taylor',attr=PlayerAttr(batting=8))
latham=Player(name='T Latham',attr=PlayerAttr(batting=7,iskeeper=True))
neesham=Player(name='J Neesham',attr=PlayerAttr(batting=6))
dgrandhome=Player(name='C de Grandhomme', attr=PlayerAttr(batting=6, bowling=7))
santner=Player(name='M Santner',attr=PlayerAttr(bowling=7))
henry=Player(name='M Henry',attr=PlayerAttr(bowling=8))
southee=Player(name='T Southee',attr=PlayerAttr(bowling=8))
boult=Player(name='T Boult',attr=PlayerAttr(bowling=8))

roy=Player(name='J Roy',attr=PlayerAttr(batting=8))
bairstow=Player(name='J Bairstow',attr=PlayerAttr(batting=7))
root=Player(name='J Root',attr=PlayerAttr(batting=8))
morgan=Player(name='E Morgan',attr=PlayerAttr(batting=8, iscaptain=True))
stokes=Player(name='B Stokes',attr=PlayerAttr(batting=7, bowling=7))
buttler=Player(name='J Buttler',attr=PlayerAttr(batting=6, iskeeper=True))
woakes=Player(name='C Woakes', attr=PlayerAttr(batting=6, bowling=7))
plunkett=Player(name='L Plunkett',attr=PlayerAttr(bowling=7))
archer=Player(name='J Archer',attr=PlayerAttr(bowling=8))
rashid=Player(name='A Rashid',attr=PlayerAttr(bowling=7))
wood=Player(name='M Wood',attr=PlayerAttr(bowling=8))
