from helper import*

extras = Player('Extra',False,0,0,True)

sachin=Player('Sachin',False, 0, 0, True)
sehwag=Player('Sehwag',False, 0, 0, True)
gambhir=Player('Gambhir',False, 0, 0, True)
kohli=Player('Kohli',False, 0, 0, True)
yuvraj=Player('Yuvraj',False, 0, 0, True)
dhoni=Player('Dhoni',False, 0, 0, True)
raina=Player('Raina',False, 0, 0, True)
ashwin=Player('Ashwin',False, 0, 0, True)
zaheer=Player('Zaheer',False, 0, 0, True)
nehra=Player('Nehra',False, 0, 0, True)
sreesanth=Player('Sreesanth',False, 0, 0, True)

hayden=Player('hayden',False, 0, 0, True)
gilchrist=Player('gilchrist',False, 0, 0, True)
ponting=Player('ponting',False, 0, 0, True)
clarke=Player('clarke',False, 0, 0, True)
hussey=Player('hussey',False, 0, 0, True)
watson=Player('watson',False, 0, 0, True)
white=Player('white',False, 0, 0, True)
hogg=Player('hogg',False, 0, 0, True)
johnson=Player('johnson',False, 0, 0, True)
lee=Player('lee',False, 0, 0, True)
tait=Player('tait',False, 0, 0, True)

tharanga=Player('tharanga',False, 0, 0, True)
dilshan=Player('dilshan',False, 0, 0, True)
sangakkara=Player('sangakkara',False, 0, 0, True)
jayawardene=Player('jayawardene',False, 0, 0, True)
samaraweera=Player('samaraweera',False, 0, 0, True)
kapugedera=Player('kapugedera',False, 0, 0, True)
kulashekara=Player('kulashekara',False, 0, 0, True)
perera=Player('perera',False, 0, 0, True)
randiv=Player('randiv',False, 0, 0, True)
malinga=Player('malinga',False, 0, 0, True)
murali=Player('murali',False, 0, 0, True)
